### ISSUE TITLE
willing to test, but unable to get Apple Thunderbolt Display recognized

### ISSUE THREAD

**Issue by pfps** [gicmo/bolt#40]
I'm willing to test boltctl.  In fact I have to test it to get Thunderbolt to work at all on Linux as my laptop doesn't have a way to turn Thunderbolt security off.   However, I'm not getting very far, and maybe not even getting far enough for boltctl to do anything useful so this might not be a problem with boltctl.

I have a Lenovo Yoga 920, which has the newish Intel Corporation JHL6540 Thunderbolt 3 chip in it.  There is no way that I know of to change Thunderbolt 3 security on the laptop.  The default state for Thunderbolt 3 security on the laptop is user security.  

My USB-C ports work fine in regular USB mode and when driving an HDMI device via a USB-C to HDMI converter.   When I plug in an Apple Thunderbolt Display attached to a Thunderbolt-3-to-2 adapter the Intel chip turns on in Thunderbolt mode and boltctl monitor emits

DeviceAdded: /org/freedesktop/bolt/devices/d5010000_0080_8f08_23b2_0d4a0952a11d

but nothing more happens.

Only the Intel chip shows up in boltctl llist
```
 * Yoga920
   |- uuid:        d5010000-0080-8f08-23b2-xxxxxx
   |- vendor:      Lenovo
   |- status:      authorized
   |  `- security: user
   `- stored:      no 
```

When running Windows the Apple Thunderbolt Display does show up bit cannot be connected and does not do anything.  So Windows is doing more than Linux, but not much more.

There are lots of things that could be going wrong here, and I'm willing to be a guinea pig.  (Except that I'm going to be away from the display for a couple of weeks.)   Where should I apply?

I'm also getting freezes in some non-Thunderbolt situations.

**Comment by gicmo** [comment]
@pfps From the output in `boltctl list` it seems that the Thunderbolt-3-to-2 adapter does itself not show up as a device? Because what you are seeing in the output there is only the host controller itself. Are there any entries in `/sys/bus/thunderbolt` for the adapter?
What exactly is not working? Does monitor show any picture at all?
Have you check the `dmesg` log? What distribution are you running? I would recommend filing a bug with them as well as I suspect that this might no be a bug related to the security level (and thus bolt).

**Comment by pfps** [comment]
@gitmo Nothing for the adapter, just for the host controller, I think

idefix thunderbolt> ls -l /sys/bus/thunderbolt/devices/
total 0
lrwxrwxrwx. 1 root root 0 Jan  2 12:05 0-0 -> ../../../devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/domain0/0-0/
lrwxrwxrwx. 1 root root 0 Jan  2 12:05 domain0 -> ../../../devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/domain0/

The monitor remains off.  (Possibly this is the problem.  The Apple Thunderbolt monitor doesn't have an on/off switch and may have to be turned on by the host.)

I'm running Fedora 27.   I'll put in a bug report there.

I looked at the system log.  There is a lot of stuff in it.  Some of it looks suspicious, also indicating the possibility of some sort of bug.

**Comment by gicmo** [comment]
@pfps ok. If the adapter does not show up there is nothing much bolt can do. Please do indeed file a bug at bugzilla.redhat.com and cc me there (ckellner@redhat) and I will see if I can get such an adaptor and can reproduce with my T470s. I will close this bug here because there is not much I can do about it.

**Comment by pfps** [comment]
OK, it's https://bugzilla.redhat.com/show_bug.cgi?id=1531929
