### ISSUE TITLE
polkit defaults

### ISSUE THREAD

**Issue by setharnold** [gicmo/bolt#73]
Hello, I'm reviewing bolt as part of the Ubuntu main inclusion request process.

I noticed in the polkit documentation:

> Keep in mind that if polkit.Result.AUTH_SELF_KEEP or
> polkit.Result.AUTH_ADMIN_KEEP is returned, authorization checks for
> the same action identifier and subject will succeed (that is, return
> polkit.Result.YES) for the next brief period (e.g. five minutes) even
> if the variables passed along with the check are different. Therefore,
> if the result of an authorization rule depend on such variables, it
> should not use the "*_KEEP" constants!

bolt's polkit files use the `keep` variants by default.

Does the thunderbolt protocol allow a device to supply multiple logical
devices? Could this allow a malicious device to be authorized legitimately
as a 'harmless' sort of device and then four minutes later silently gain
new capabilities?

Thanks

**Comment by ybernat** [comment]
The common assumption is that the users knows what they are connecting to their systems.
All the security scheme is directed to mitigate the threat of a device connected when the user isn't aware of.
Does it answers the question?

**Comment by gicmo** [comment]
@ybernat is 100% correct. The thread model that we want to prevent is someone plugging in a 'evil' device while the user away. Basically, the act of plugging in the device itself by an authorized user is seen as the intent to use, hence authorize it. For general users that are admins (i.e. people in the 'wheel') the policy rules allow device enrollment/authorization without any password dialog at all *if* the session is unlocked. For non-admins the auth dialog is taken as a proof that one is admin and allowed to authorize devices. 
I also don't think that throwing up two auth dialogs in a row for an evil device with one additional "virtual" device would actually help because if the evil virtual device is the first in the chain the user would authorize it and when the second dialog comes up it is already game over.
I hope that @ybernat and mine explanation are convincing enough. ;)

**Comment by setharnold** [comment]
Thank you both for your thoughts, and work on bolt. I'm more content with
the 'keep' authorization now.

Thanks
